---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: False
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    - name: Create molecule instance(s)
      epc_vm:
        description: "{{ item.name | default('auto_molecule_epc_instance') }}"
        access_id: "{{ item.access_id | default(omit) }}"
        token: "{{ item.token | default(omit) }}"
        region: "{{ item.region | default(omit) }}"
        project: "{{ item.project | default(omit) }}"
        shape: "{{ item.shape }}"
        image: "{{ item.image }}"
        ignore_ssl: "{{ item.ignore_ssl | default(True) }}"
        instance_id: "{{ item.instance_id | default(omit) }}"
        ssh_key: "{{ item.ssh_key | default(omit) }}"
        wait_timeout: "{{ item.wait_timeout | default(1200) }}"
        state: run
      register: server
      with_items: "{{ molecule_yml.platforms }}"

    # Mandatory configuration for Molecule to function.
    - name: Populate instance config dict
      set_fact:
        instance_conf_dict:
          autoconfiguration_state: "{{ item.autoConfigurationState }}"
          created: "{{ item.created }}"
          image: "{{ item.image }}"
          instance_id: "{{ item.instanceId }}"
          isexposed: "{{  item.isExposed }}"
          last_processed_by_autoconfiguration_state: "{{ item.lastProcessedByAutoConfigurationState }}"
          owner: "{{ item.owner }}"
          processed_by_autoconfiguration: "{{ item.processedByAutoConfiguration }}"
          project: "{{ item.project }}"
          scan_counter: "{{ item.scanCounter }}"
          scan_counter_within_period: "{{ item.scanCounterWithinPeriod }}"
          shape: "{{ item.shape }}"
          description: "{{ item.description }}"
          ssh_keyset: "{{ item.sshKeySet }}"
          state: "{{ item.state }}"
          region: "{{ item.zone }}"
      with_items: "{{ server.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        # NOTE(retr0h): Workaround for Ansible 2.2.
        #               https://github.com/ansible/ansible/issues/20885
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool
