---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: epc
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: test-atg-platform
    image: CentOS6_64-bit
    shape: large
    region: AWS-EUCENTRAL
    wait_timeout: 1800
    groups:
      - atg-platform
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws
verifier:
  name: testinfra
  lint:
    name: flake8
