---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos6-atg-platform-11.1
    image: centos:6
    privileged: True
    groups:
      - rhel_family
      - atg_platform_11_1
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
scenario:
  name: docker-11.1
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
