---
# Run all tests
stages:
  - lint
  - Deployment test

# Check OS, ansible, molecule, docker version
before_script:
  - ansible --version
  - molecule --version
  - docker --version

variables:
  GET_SOURCES_ATTEMPTS: "5"
  ANSIBLE_INVENTORY: "/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible/inventory/epc.py"
  ANSIBLE_LIBRARY: "/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible"
  ANSIBLE_INVENTORY_PLUGINS: "/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible/inventory/epc.py"

# Tests for Docker driver for ATG 11.3
.Docker atg-platform 11.3:
  stage: Deployment test
  script:
    - molecule test -s docker-11.3
  tags:
    - molecule2.16

# Tests for EPC driver for ATG 11.3
EPC atg-platform 11.3:
  variables:
    EPC_REGION: EPAM-BY2
  stage: Deployment test
  script:
    - molecule test -s cloud-epc
  tags:
    - molecule2.16

# Tests for AWS driver for ATG 11.3
AWS] atg-platform 11.3:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: Deployment test
  script:
    - molecule test -s cloud-aws
  tags:
    - molecule2.16

# Tests for Docker driver for ATG 10.1.1
.Docker atg-platform 10.1.1:
  stage: Deployment test
  script:
    - molecule test -s docker-10.1.1
  tags:
    - molecule2.16

# Tests for Docker driver for ATG 10.2
.Docker atg-platform 10.2:
  stage: Deployment test
  script:
    - molecule test -s docker-10.2
  tags:
    - molecule2.16

# Tests for Docker driver for ATG 11.1
.Docker atg-platform 11.1:
  stage: Deployment test
  script:
    - molecule test -s docker-11.1
  tags:
    - molecule2.16

# Tests for Docker driver for ATG 11.2
.Docker atg-platform 11.2:
  stage: Deployment test
  script:
    - molecule test -s docker-11.2
  tags:
    - molecule2.16
