---
# Run all tests
stages:
  - lint
  - Deployment test

# Check OS, ansible, molecule, docker version
before_script:
  - ansible --version
  - molecule --version
  - docker --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

# Tests for Docker driver for ATG 11.2
.Docker atg-platform 11.2:
  stage: Deployment test
  script:
    - molecule test -s docker-11.2
  tags:
    - molecule2.16

# Tests for delegated driver for ATG 11.2
EPC[Delegated] atg-platform 11.2:
  variables:
    EPC_REGION: EPAM-BY2
  stage: Deployment test
  script:
    - molecule test -s cloud-epc-delegated
  tags:
    - molecule2.16

# Tests for AWS driver for ATG 11.2
AWS[Delegated] atg-platform 11.2:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: Deployment test
  script:
    - molecule test -s cloud-aws-delegated
  tags:
    - molecule2.16

# Tests for Docker driver for ATG 10.1.1
.Docker atg-platform 10.1.1:
  stage: Deployment test
  script:
    - molecule test -s docker-10.1.1
  tags:
    - molecule2.16

# Tests for Docker driver for ATG 10.2
.Docker atg-platform 10.2:
  stage: Deployment test
  script:
    - molecule test -s docker-10.2
  tags:
    - molecule2.16

# Tests for Docker driver for ATG 11.1
.Docker atg-platform 11.1:
  stage: Deployment test
  script:
    - molecule test -s docker-11.1
  tags:
    - molecule2.16
