---
# Check OS, ansible, molecule, docker version
before_script:
  - pip install --upgrade ansible==2.5.5 ansible-lint==3.4.21 docker-py==1.10.6 molecule==2.13.1 pyOpenSSL PyYAML==3.12
  - ansible --version
  - molecule --version
  - docker --version

# Run all tests
stages:
  - lint
  - Deployment test

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`
  after_script:
    - rm -rf ~/ansible-lint-rules

# Tests for Docker driver for ATG 11.2
Docker atg-platform 11.2:
  stage: Deployment test
  script:
    - molecule test -s docker-11.2

# Tests for Docker driver for ATG 10.1.1
Docker atg-platform 10.1.1:
  stage: Deployment test
  script:
    - molecule test -s docker-10.1.1

# Tests for Docker driver for ATG 10.2
Docker atg-platform 10.2:
  stage: Deployment test
  script:
    - molecule test -s docker-10.2

# Tests for Docker driver for ATG 11.1
Docker atg-platform 11.1:
  stage: Deployment test
  script:
    - molecule test -s docker-11.1
