---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - ansible-lint --version
  - molecule --version
  - ansible-config dump --only-changed

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws

# Tests for EPC driver for ATG 11.3
EPC atg-platform 11.3:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated

# Tests for AWS driver for ATG 11.3
AWS atg-platform 11.3:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-11.3
  tags:
    - aws

# Tests for Docker driver for ATG 10.x
Docker atg-platform 10.x:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s docker-10.x
  tags:
    - aws

# Tests for Docker driver for ATG 11.1
Docker atg-platform 11.1:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s docker-11.1
  tags:
    - aws

# Tests for Docker driver for ATG 11.2
Docker atg-platform 11.2:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s docker-11.2
  tags:
    - aws

# Tests for Docker driver for ATG 11.3
Docker atg-platform 11.3:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s docker-11.3
  tags:
    - aws
