---
dist: xenial
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - pip install --upgrade ansible==2.5.7 ansible-lint molecule
  - ansible --version
  - molecule lint
  - molecule syntax

script:
  - ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/ 
