---
- name: "Check {{ config_properties_txt }}"
  stat:
    path: "{{ config_properties_txt }}"
  register: conf_props

- name: "Read config file"
  include_tasks: "read-atg-conf-props.yml"
  when: conf_props.stat.exists | bool

- name: "Install ATG"
  include_tasks: "install-platform.yml"
  when: (not conf_props.stat.exists | bool) or not atg_version == atg_installed_version
