---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.jboss
      transport: "web"
      transport_web: "https://touch.epm-esp.projects.epam.com/static-files/oracle-commerce-suite/app-servers/jboss-eap-6.1.0.zip"
    - role: atg-platform
      transport: "web"
      atg_version: "10.2"
      transport_web: "https://touch.epm-esp.projects.epam.com/static-files/oracle-commerce-suite/commerce/ATG10.2/ATG10.2/ATG10.2.zip"
