# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN yum makecache fast && yum update -y && yum -y install initscripts systemd-sysv redhat-lsb-core sudo bash iproute libselinux-python libsemanage-python \
    yum-plugin-ovl && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all;

RUN if [ -f /sbin/agetty ]; then cp /bin/true /sbin/agetty; \
    elif [ -f /sbin/mingetty ]; then cp /bin/true /sbin/mingetty; fi
