---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos6-ansible-role-atg-platform-10.1.1
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - rhel_family
      - atg_platform_10_1_1

  - name: test-docker-centos6-ansible-role-atg-platform-10.2
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - rhel_family
      - atg_platform_10_2
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
scenario:
  name: docker-10.x
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
