---
- name: Converge
  hosts: atg_platform_10_1_1
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.jboss
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/app-servers/jboss-eap-6.1.0.zip"
    - role: ansible-role-atg-platform
      atg_version: "10.1.1"
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/commerce/ATG10.1.1/ATG10.1.1.zip"

- name: Converge
  hosts: atg_platform_10_2
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.jboss
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/app-servers/jboss-eap-6.1.0.zip"
    - role: ansible-role-atg-platform
      transport: "web"
      atg_version: "10.2"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/commerce/ATG10.2/ATG10.2/ATG10.2.zip"
